### ISSUE TITLE
Starting the project

### ISSUE THREAD

**Issue by Michael-Briere** [code987-bio/Inheritance#1]
Hey! 

When I have a task like that one, I like to divide it into smaller, easier tasks. I think it will be useful for you, as you are new to programming. So take some time to think about which feature your program should include and plan from there.

So for a timekeeping management system, you might have a plan looking like this:
- Give the user the choice of an action (add a new entry, modify an existing entry, etc.)
- Program each option individually (probably each with a function/method)
...

And so on and so forth. Since you need a superclass and subclasses, I would think about what could constitute a good class to work with. There are many options, for example an Employee class.

The best piece of advice I can give you is to just jump in and try to code it yourself. You will learn better that way, in my opinion.

**Comment by Michael-Briere** [comment]
Hey again. You said you added new content, but I can't see it. Have you committed your changes?

**Comment by code987-bio** [comment]
I'm new to the software/website so I didn't see your message until now.  Let me try to figure out what committing changes is and get back to you!

**Comment by Michael-Briere** [comment]
No problem. We all have to start somewhere. I am myself new to Github. To upload your .pi files, you can go to the code tab above, then add files > upload files. You can then drop your files in there. Finally, you can click Commit to make the changes.
